UPDATE CONSOLE_UPDATE SET UPDATE_COMPLETE=1,UPDATE_INSTALLED_ON=NOW() WHERE UPDATE_VERSION='1.7.1';
ALTER TABLE console_file ADD tag VARCHAR(8192) DEFAULT NULL BEFORE app_name;
CREATE TABLE CONSOLE_RESOURCE_TAG (
   id BIGINT IDENTITY PRIMARY KEY,
   name VARCHAR(255) NOT NULL UNIQUE
);
