// Exercises every MCP tool once against a running Dev server and fails if a tool was not covered.
// usage: node mcp/scenarios/tools.mjs [appName]
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { startMcp, check, summary } from './lib.mjs';

// app names are letters only
const app = process.argv[2] || 'tools' + [...Array(6)].map(() => String.fromCharCode(97 + Math.floor(Math.random() * 26))).join('');
const mcp = startMcp();
await mcp.init();
const covered = new Set();
const call = async (name, args) => {
  covered.add(name);
  return mcp.call(name, args);
};

const resourceXml = (extra = '') => `<?xml version="1.0" encoding="UTF-8" ?>
<Resource xmlns="http://xml.metamug.net/resource/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://xml.metamug.net/resource/1.0 http://xml.metamug.net/schema/resource.xsd" v="1.0">
  <Request method="GET"><Script id="s" file="hello"/>${extra}</Request>
</Resource>`;

console.log('== apps ==');
check('list_apps', (await call('list_apps')).status === 200);
const created = await call('create_app', { id: app, desc: 'tool coverage' });
check('create_app', created.status === 201, created.text);
check('wait_for_app', (await call('wait_for_app', { app })).status === 200);

console.log('== sql ==');
const ddl = await call('run_sql', { app, type: 'query', sql: 'CREATE TABLE note (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, body VARCHAR(100))' });
check('run_sql DDL', ddl.status === 200 && (ddl.json?.[0]?.status ?? 200) < 400, ddl.text);

console.log('== scripts ==');
const up = await call('upload_script', { app, filename: 'hello.kts', content: 'response["v"] = 1\n' });
check('upload_script creates', /created/.test(up.text) && /20[01]/.test(up.text), up.text);
const up2 = await call('upload_script', { app, filename: 'hello.kts', content: 'response["v"] = 2\n' });
check('upload_script updates an existing script', /updated/.test(up2.text) && /HTTP 200/.test(up2.text), up2.text);
const ls = await call('list_scripts', { app });
check('list_scripts shows it', /hello/.test(ls.text), ls.text);
const gs = await call('get_script', { app, name: 'hello' });
check('get_script returns the updated source', /v"\] = 2/.test(gs.text), gs.text);

console.log('== resources ==');
const def = await call('define_resource', { app, name: 'hello', xml: resourceXml() });
check('define_resource (create + deploy)', /deployed":true/.test(def.text), def.text);
check('list_resources', /hello/.test((await call('list_resources', { app })).text));
check('get_resource', /<Resource/.test((await call('get_resource', { app, name: 'hello', version: 'v1.0' })).text));
check('deployment_status', /"deployed":true/.test((await call('deployment_status', { app })).text));
check('deploy_backend', /"deployed":true/.test((await call('deploy_backend', { app })).text));

console.log('== runtime ==');
const hit = await call('call_endpoint', { method: 'GET', path: `/${app}/v1.0/hello` });
check('call_endpoint', hit.status === 200 && hit.json?.s?.v === 2, hit.text);
check('get_stats', /resourcecount|\{/.test((await call('get_stats', { app })).text));

console.log('== errors ==');
await call('upload_script', { app, filename: 'hello.kts', content: 'response["v"] = nope\n' });
const bad = await call('call_endpoint', { method: 'GET', path: `/${app}/v1.0/hello` });
check('call_endpoint reports an errorId and hints at get_errors', bad.status === 512 && /get_errors/.test(bad.text), bad.text);
const errId = bad.body.match(/"errorId":"(\d+)"/)?.[1];
const err = await call('get_errors', { app, errorId: errId });
check('get_errors returns the compile error with its line', /Unresolved reference: nope \(line 1:/.test(err.text), err.text);

console.log('== apply_project (a whole folder in one call) ==');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'r2proj-'));
fs.mkdirSync(path.join(dir, 'scripts'));
fs.mkdirSync(path.join(dir, 'resources'));
fs.writeFileSync(path.join(dir, 'schema.sql'), 'CREATE TABLE pnote (id INT PRIMARY KEY, body VARCHAR(50))\n;\nINSERT INTO pnote VALUES (1, \'x\')\n');
fs.writeFileSync(path.join(dir, 'scripts', 'proj.kts'), 'response["from"] = "project"\n');
fs.writeFileSync(path.join(dir, 'resources', 'proj.xml'), resourceXml().replace('file="hello"', 'file="proj"').replace('<Script id="s"', '<Script id="p"'));
const ap = await call('apply_project', { app, dir });
check('apply_project deploys schema, script and resource in one call', ap.status === 200 && /schema: 2\/2/.test(ap.text) && /ok\s+script proj\.kts/.test(ap.text) && /ok\s+resource proj\.xml/.test(ap.text), ap.text);
const pj = await call('call_endpoint', { method: 'GET', path: `/${app}/v1.0/proj` });
check('the applied project is served', pj.json?.p?.from === 'project', pj.text);
fs.writeFileSync(path.join(dir, 'resources', 'broken.xml'), '<Resource v="1.0"><oops/></Resource>');
const apBad = await call('apply_project', { app, dir, skipSchema: true });
check('apply_project reports a broken item without hiding the others', apBad.status === 422 && /FAIL resource broken\.xml/.test(apBad.text) && /ok\s+resource proj\.xml/.test(apBad.text), apBad.text);
fs.rmSync(dir, { recursive: true, force: true });

console.log('== cleanup ==');
const del = await call('delete_script', { app, name: 'hello' });
check('delete_script', del.status === 410, del.text);
check('script is gone from list_scripts', !/hello/.test((await call('list_scripts', { app })).text));
check('delete_resource', (await call('delete_resource', { app, name: 'hello', version: 'v1.0' })).status < 500);
check('delete_app', (await call('delete_app', { app })).status === 410);

const all = (await mcp.tools()).map((t) => t.name);
const missed = all.filter((n) => !covered.has(n));
check(`every tool is covered (${all.length} tools)`, missed.length === 0, `not covered: ${missed.join(', ')}`);

mcp.close();
process.exit(summary() ? 0 : 1);
