//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.06 at 11:04:34 AM IST 
//
package net.metamug.xml.resource._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for method.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="method"> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration value="GET"/> &lt;enumeration value="POST"/> &lt;enumeration value="PUT"/>
 * &lt;enumeration value="DELETE"/> &lt;/restriction> &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "method")
@XmlEnum
public enum Method {

    GET,
    POST,
    PUT,
    DELETE;

    public String value() {
        return name();
    }

    public static Method fromValue(String v) {
        return valueOf(v);
    }

}
