//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 01:54:54 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.metamug.net/resource/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.metamug.xml.resource._1;
