//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.06 at 11:04:34 AM IST 
//
package net.metamug.xml.resource._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * For processing incoming request and sending back response.
 *
 *
 * <p>
 * Java class for request complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Desc" type="{http://xml.metamug.net/resource/1.0}desc" minOccurs="0"/>
 *         &lt;element name="Param" type="{http://xml.metamug.net/resource/1.0}param" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Execute" type="{http://xml.metamug.net/resource/1.0}execute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Filter" type="{http://xml.metamug.net/resource/1.0}execute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Query" type="{http://xml.metamug.net/resource/1.0}query" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Update" type="{http://xml.metamug.net/resource/1.0}update" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://xml.metamug.net/resource/1.0}id" />
 *       &lt;attribute name="method" use="required" type="{http://xml.metamug.net/resource/1.0}method" />
 *       &lt;attribute name="status" type="{http://xml.metamug.net/resource/1.0}status" />
 *       &lt;attribute name="item" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request", propOrder = {
    "descOrParamOrExecute"
})
public class Request {

    @XmlElementRefs({
        @XmlElementRef(name = "Desc", namespace = "http://xml.metamug.net/resource/1.0", type = JAXBElement.class, required = false)
        ,
        @XmlElementRef(name = "Filter", namespace = "http://xml.metamug.net/resource/1.0", type = JAXBElement.class, required = false)
        ,
        @XmlElementRef(name = "Update", namespace = "http://xml.metamug.net/resource/1.0", type = JAXBElement.class, required = false)
        ,
        @XmlElementRef(name = "Execute", namespace = "http://xml.metamug.net/resource/1.0", type = JAXBElement.class, required = false)
        ,
        @XmlElementRef(name = "Query", namespace = "http://xml.metamug.net/resource/1.0", type = JAXBElement.class, required = false)
        ,
        @XmlElementRef(name = "Param", namespace = "http://xml.metamug.net/resource/1.0", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> descOrParamOrExecute;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "method", required = true)
    protected Method method;
    @XmlAttribute(name = "status")
    protected Integer status;
    @XmlAttribute(name = "item")
    protected Boolean item;

    /**
     * Gets the value of the descOrParamOrExecute property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the descOrParamOrExecute property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescOrParamOrExecute().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null     {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Query }{@code >}
     * {@link JAXBElement }{@code <}{@link Param }{@code >}
     * {@link JAXBElement }{@code <}{@link Execute }{@code >}
     * {@link JAXBElement }{@code <}{@link Update }{@code >}
     * {@link JAXBElement }{@code <}{@link Execute }{@code >}
     *
     *
     */
    public List<JAXBElement<?>> getDescOrParamOrExecute() {
        if (descOrParamOrExecute == null) {
            descOrParamOrExecute = new ArrayList<JAXBElement<?>>();
        }
        return this.descOrParamOrExecute;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the method property.
     *
     * @return possible object is {@link Method }
     *
     */
    public Method getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     *
     * @param value allowed object is {@link Method }
     *
     */
    public void setMethod(Method value) {
        this.method = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setStatus(Integer value) {
        this.status = value;
    }

    /**
     * Gets the value of the item property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public boolean isItem() {
        if (item == null) {
            return false;
        } else {
            return item;
        }
    }

    /**
     * Sets the value of the item property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setItem(Boolean value) {
        this.item = value;
    }

}
