//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.06 at 11:04:34 AM IST 
//
package net.metamug.xml.resource._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{http://xml.metamug.net/resource/1.0}request" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://xml.metamug.net/resource/1.0}id" />
 *       &lt;attribute name="v" use="required" type="{http://xml.metamug.net/resource/1.0}version" />
 *       &lt;attribute name="parent" type="{http://xml.metamug.net/resource/1.0}parent" />
 *       &lt;attribute name="auth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request"
})
@XmlRootElement(name = "Resource")
public class Resource {

    @XmlElement(name = "Request", required = true)
    protected List<Request> request;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "v", required = true)
    protected double v;
    @XmlAttribute(name = "parent")
    protected String parent;
    @XmlAttribute(name = "auth")
    protected String auth;

    /**
     * Gets the value of the request property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the request property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequest().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Request }
     *
     *
     */
    public List<Request> getRequest() {
        if (request == null) {
            request = new ArrayList<Request>();
        }
        return this.request;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the v property.
     *
     */
    public double getV() {
        return v;
    }

    /**
     * Sets the value of the v property.
     *
     */
    public void setV(double value) {
        this.v = value;
    }

    /**
     * Gets the value of the parent property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the auth property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAuth() {
        return auth;
    }

    /**
     * Sets the value of the auth property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAuth(String value) {
        this.auth = value;
    }

}
