// Shop scenario: scripts + SQL + mpath + branching + transactions + external calls, driven only through the MCP tools.
// usage: node mcp/scenarios/shop/run.mjs [appName]
//   env: R2_USER/R2_PASSWORD/R2_CONSOLE_URL/R2_RUNTIME_URL as for mcp/server.mjs
//        R2_DB=postgresql R2_DB_URL=localhost:5432/r2test R2_DB_USER=postgres R2_DB_PASS=postgres for an external db
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startMcp, read, check, summary } from '../lib.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const app = process.argv[2] || 'shop';
const runtime = (process.env.R2_RUNTIME_URL || 'http://localhost:7000').replace(/\/$/, '');
const pg = process.env.R2_DB === 'postgresql';
const mcp = startMcp();
await mcp.init();

const base = `/${app}/v1.0`;
const sql = (q) => mcp.call('run_sql', { app, type: 'query', sql: q });
const has = (r, text) => String(r.body).toLowerCase().includes(String(text).toLowerCase());
const rows = (r, key) => r.json?.[key] || [];

console.log(`== setup (${pg ? 'postgresql' : 'hsqldb'}) ==`);
const created = await mcp.call('create_app', {
  id: app,
  desc: 'shop scenario',
  ...(pg ? { dbtype: 'postgresql', dburl: process.env.R2_DB_URL, dbuser: process.env.R2_DB_USER, dbpass: process.env.R2_DB_PASS } : {}),
});
check('create_app', created.status === 201 || created.status === 409, created.text);
const ready = await mcp.call('wait_for_app', { app });
check('wait_for_app', ready.status === 200, ready.text);

const schema = read(here, 'schema.sql')
  .split(/;\s*\n/)
  .map((s) => s.trim())
  .filter(Boolean);
for (const q of schema) {
  const r = await sql(pg ? q.replace(/INT GENERATED BY DEFAULT AS IDENTITY \(START WITH 1\)/g, 'SERIAL') : q);
  if (r.status !== 200 || (r.json?.[0]?.status ?? 200) >= 400) console.log('  schema note:', q.slice(0, 40), r.body.slice(0, 120));
}

for (const s of ['hashpw', 'ordercalc', 'transition']) {
  const r = await mcp.call('upload_script', { app, filename: `${s}.kts`, content: read(here, 'scripts', `${s}.kts`) });
  check(`upload_script ${s}`, r.status === 200 || r.status === 201, r.text);
}
for (const rsc of ['product', 'customer', 'order']) {
  const xml = read(here, 'resources', `${rsc}.xml`).replaceAll('{{app}}', app).replaceAll('{{runtime}}', runtime);
  const r = await mcp.call('define_resource', { app, name: rsc, xml });
  check(`define_resource ${rsc}`, /deployed":true/.test(r.text), r.text);
}

console.log('== customer: script -> mpath -> sql ==');
const reg = await mcp.call('call_endpoint', { method: 'POST', path: `${base}/customer`, body: { name: 'Ada', email: 'ada@example.com', password: 'secret' } });
check('register returns declared 201', reg.status === 201, reg.text);
check('register returns the created row', has(reg, 'ada@example.com'), reg.body);

const stored = await sql("SELECT pw_hash FROM customer WHERE email = 'ada@example.com'");
const hash = JSON.stringify(stored.json).match(/[0-9a-f]{8}\$[0-9a-f]{64}/i)?.[0];
check('password stored as salted sha-256 (salt$hex), not plaintext', !!hash && !has(stored, 'secret'), stored.body);

const dup = await mcp.call('call_endpoint', { method: 'POST', path: `${base}/customer`, body: { name: 'Ada2', email: 'ada@example.com', password: 'x' } });
check('duplicate email is rejected (not 2xx)', dup.status >= 400, dup.text);
const errId = dup.body.match(/"errorId":"(\d+)"/)?.[1];
if (errId) {
  const e = await mcp.call('get_errors', { app, errorId: errId });
  check('get_errors explains the duplicate (unique constraint)', /unique|duplicate|constraint/i.test(e.text), e.text);
}

for (const [name, email, password] of [['Grace', 'grace@example.com', 'p2'], ['Linus', 'linus@example.com', 'p3']]) {
  await mcp.call('call_endpoint', { method: 'POST', path: `${base}/customer`, body: { name, email, password } });
}

console.log('== customer: collection, branching, item ==');
const all = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/customer` });
check('collection lists all 3', rows(all, 'all').length === 3, all.body);
const recent = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/customer`, query: { q: 'recent' } });
check('?q=recent branch returns the 2 newest', rows(recent, 'recent').length === 2 && !recent.json?.all, recent.body);
const one = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/customer/1` });
check('item request returns customer 1', has(one, 'ada@example.com') && rows(one, 'one').length === 1, one.body);
const none = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/customer/999` });
check('missing item returns empty result', rows(none, 'one').length === 0, none.body);

const ada = (await sql("SELECT id FROM customer WHERE email = 'ada@example.com'")).json?.[0]?.data?.[0]?.[0] ?? 1;

console.log('== order: xrequest + script + transaction + external call in one request ==');
const o1 = await mcp.call('call_endpoint', { method: 'POST', path: `${base}/order`, body: { customer_id: String(ada), product_id: '1', qty: '3' } });
check('place order returns declared 201', o1.status === 201, o1.text);
check('script priced the order from the xrequest product (3 x 4.50 = 13.5)', Number(o1.json?.calc?.total) === 13.5, o1.body);
const token = o1.json?.calc?.token;
check('script returned an HMAC token (40 hex)', /^[0-9a-f]{40}$/.test(token || ''), o1.body);
check('final SQL step returns the placed order joined with the customer', has(o1, 'Ada') && has(o1, 'NEW'), o1.body);
const stock = await sql('SELECT stock FROM product WHERE id = 1');
check('transaction decremented stock 100 -> 97', JSON.stringify(stock.json).includes('97'), stock.body);
const lines = await sql('SELECT COUNT(*) FROM order_line');
check('transaction wrote the order line', JSON.stringify(lines.json).includes('1'), lines.body);

const bad = await mcp.call('call_endpoint', { method: 'POST', path: `${base}/order`, body: { customer_id: String(ada), product_id: '1', qty: '1000' } });
check('insufficient stock: script rejects, no transaction run', has(bad, 'insufficient stock') && !has(bad, '"placed"'), bad.body);
const stock2 = await sql('SELECT stock FROM product WHERE id = 1');
check('stock unchanged after the rejected order', JSON.stringify(stock2.json).includes('97'), stock2.body);
const unk = await mcp.call('call_endpoint', { method: 'POST', path: `${base}/order`, body: { customer_id: String(ada), product_id: '999', qty: '1' } });
check('unknown product is rejected by the script', has(unk, 'unknown product'), unk.body);

console.log('== order: item (joins), collection branching, state machine ==');
const orderId = o1.json?.placed?.[0]?.ID ?? o1.json?.placed?.[0]?.id ?? 1;
const item = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/order/${orderId}` });
check('item request joins order, customer and lines', has(item, 'Ada') && has(item, 'Notebook') && rows(item, 'lines').length === 1, item.body);
const byC = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/order`, query: { customer_id: String(ada) } });
check('?customer_id branch', rows(byC, 'byCustomer').length === 1 && !byC.json?.all, byC.body);
const byS = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/order`, query: { status: 'PAID' } });
check('?status branch (no PAID orders yet)', rows(byS, 'byStatus').length === 0 && !byS.json?.all, byS.body);
const allO = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/order` });
check('no filter returns all orders', rows(allO, 'all').length === 1, allO.body);

const ship = await mcp.call('call_endpoint', { method: 'PUT', path: `${base}/order/${orderId}`, body: { status: 'SHIPPED' } });
check('NEW -> SHIPPED is refused by the state machine script', has(ship, 'cannot go from NEW to SHIPPED'), ship.body);
const pay = await mcp.call('call_endpoint', { method: 'PUT', path: `${base}/order/${orderId}`, body: { status: 'PAID' } });
check('NEW -> PAID accepted, declared 202', pay.status === 202, pay.text);
const after = await mcp.call('call_endpoint', { method: 'GET', path: `${base}/order/${orderId}` });
check('status is now PAID', has(after, 'PAID'), after.body);

mcp.close();
process.exit(summary() ? 0 : 1);
