CREATE TABLE customer (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL UNIQUE, pw_hash VARCHAR(200) NOT NULL);
CREATE TABLE product (id SERIAL PRIMARY KEY, sku VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, price DECIMAL(10,2) NOT NULL, stock INT NOT NULL);
CREATE TABLE orders (id SERIAL PRIMARY KEY, customer_id INT NOT NULL, total DECIMAL(10,2) NOT NULL, status VARCHAR(20) NOT NULL, token VARCHAR(80));
CREATE TABLE order_line (id SERIAL PRIMARY KEY, order_id INT NOT NULL, product_id INT NOT NULL, qty INT NOT NULL, price DECIMAL(10,2) NOT NULL);
INSERT INTO product (sku, name, price, stock) VALUES ('BK-001', 'Notebook', 4.50, 100);
INSERT INTO product (sku, name, price, stock) VALUES ('PN-002', 'Pen', 1.25, 500);
