//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.04.19 at 06:43:03 PM IST
//
package com.metamug.parser.schema;

import java.util.*;
import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "Desc")
public class Desc {

    protected List<Tag> tags = new ArrayList<>();
    protected List<String> desc = new ArrayList<>();
    
    @XmlElementRef(name="Tag",type=Tag.class)
    public List<Tag> getTags() {
        return tags;
    }
    
    @XmlMixed
    public List<String> getDesc() {
        return desc;
    }

    public void setDesc(String value) {
        desc = new ArrayList<>();
        desc.add(value);
    }

    public void setTag(Tag tag) {
        tags = new ArrayList<>();
        tags.add(tag);
    }
    
    public void setTag(String tagXml) throws JAXBException{
        if(!tagXml.equals("")){
            Tag tag = (Tag)new Tag().unmarshal(tagXml);
            setTag(tag);
        }else{
            tags = new ArrayList<>();
        }
    }
}