drop table request_log;
drop table query_log;
drop table error_log;
drop table usr;
drop table usr_role;
drop table mtg_query_reference;
drop table mtg_query_test_data;
drop table mtg_query_tag;
drop table mtg_query_catalog;