//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.02 at 06:40:50 PM IST 
//
package com.metamug.jaxb.gener;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resource }
     *
     * @return
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Request }
     *
     * @return
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Create }
     *
     * @return
     */
    public Create createCreate() {
        return new Create();
    }

    /**
     * Create an instance of {@link Read }
     *
     * @return
     */
    public Read createRead() {
        return new Read();
    }

    /**
     * Create an instance of {@link Update }
     *
     * @return
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link Delete }
     *
     * @return
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link Sql }
     *
     * @return
     */
    public Sql createSql() {
        return new Sql();
    }

}
