//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.07 at 10:53:17 AM IST 
//
package com.metamug.jaxb.gener;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request",  propOrder = {
    "descOrParamOrExecute"
})
public class Request {
    @XmlElements({
        @XmlElement(name = "Desc", type = String.class),
        @XmlElement(name = "Param", type = Param.class),
        @XmlElement(name = "Execute", type = Execute.class),
        @XmlElement(name = "Sql", type = Sql.class)
    })
    protected List<Object> descOrParamOrExecute;
    @XmlAttribute(name = "method", required = true)
    protected Method method;
    @XmlAttribute(name = "item")
    protected Boolean item;
    
    public Request() {
    }

    public Request(Method method) {
        this.method = method;
    }
    
    public List<Object> getDescOrParamOrExecute() {
        if (descOrParamOrExecute == null) {
            descOrParamOrExecute = new ArrayList<Object>();
        }
        return this.descOrParamOrExecute;
    }
    
    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link Method }
     *     
     */
    public Method getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link Method }
     *     
     */
    public void setMethod(Method value) {
        this.method = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isItem() {
        if (item == null) {
            return false;
        } else {
            return item;
        }
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setItem(Boolean value) {
        this.item = value;
    }

}
