//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.07 at 10:53:17 AM IST 
//
package com.metamug.jaxb.gener;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for request complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="desc" type="{}desc" minOccurs="0"/>
 *         &lt;element name="Sql" type="{}sql" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="method" type="{}method" default="GET" />
 *       &lt;attribute name="id" type="{}id" />
 *       &lt;attribute name="out" type="{}out" default="json" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request", propOrder = {
    "desc",
    "sql"
})
@XmlSeeAlso({
    Create.class,
    Read.class,
    Update.class,
    Delete.class
})
public class Request {

    protected String desc;
    @XmlElement(name = "Sql", required = true)
    protected List<Sql> sql;
    @XmlAttribute(name = "method")
    protected Method method;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "out")
    protected Out out;

    public Request() {

    }

    public Request(Method method) {
        this.method = method;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the sql property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the sql property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSql().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Sql }
     *
     *
     * @return
     */
    public List<Sql> getSql() {
        if (sql == null) {
            sql = new ArrayList<>();
        }
        return this.sql;
    }

    /**
     * Gets the value of the method property.
     *
     * @return possible object is {@link Method }
     *
     */
    public Method getMethod() {
        if (method == null) {
            return Method.GET;
        } else {
            return method;
        }
    }

    /**
     * Sets the value of the method property.
     *
     * @param value allowed object is {@link Method }
     *
     */
    public void setMethod(Method value) {
        this.method = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link Long }
     *
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the out property.
     *
     * @return possible object is {@link Out }
     *
     */
    public Out getOut() {
        if (out == null) {
            return Out.JSON;
        } else {
            return out;
        }
    }

    /**
     * Sets the value of the out property.
     *
     * @param value allowed object is {@link Out }
     *
     */
    public void setOut(Out value) {
        this.out = value;
    }

}
