name: R2 Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Build web assets with node
        run: sh ui/build.sh
        env:
          CI: false
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: sh build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Metamug API Server
          path: |
            server/api-console
          # !dist/**/*.md
